# Generated by Django 3.1.2 on 2020-10-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('juego', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis.autor')),
                ('genero', models.ManyToManyField(to='analisis.Genero')),
            ],
        ),
    ]
